INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_OFDM_SHORT_PREAMBLE ofdm_short_preamble)

FIND_PATH(
    OFDM_SHORT_PREAMBLE_INCLUDE_DIRS
    NAMES ofdm_short_preamble/api.h
    HINTS $ENV{OFDM_SHORT_PREAMBLE_DIR}/include
        ${PC_OFDM_SHORT_PREAMBLE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    OFDM_SHORT_PREAMBLE_LIBRARIES
    NAMES gnuradio-ofdm_short_preamble
    HINTS $ENV{OFDM_SHORT_PREAMBLE_DIR}/lib
        ${PC_OFDM_SHORT_PREAMBLE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OFDM_SHORT_PREAMBLE DEFAULT_MSG OFDM_SHORT_PREAMBLE_LIBRARIES OFDM_SHORT_PREAMBLE_INCLUDE_DIRS)
MARK_AS_ADVANCED(OFDM_SHORT_PREAMBLE_LIBRARIES OFDM_SHORT_PREAMBLE_INCLUDE_DIRS)

